version: '3.5'
volumes:
    prometheus_data: {}
    grafana_data: {}
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: SergioArroni
      MONGO_INITDB_ROOT_PASSWORD: julio321
      MONGO_INITDB_DATABASE: DeDesktop
    ports:
      - "27017:27017"
  python:
    build: ./data
    image: python
    ports:
      - "8000:8000"
    depends_on: 
      - mongo
